# Starter pipeline
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
- task: BatchScript@1
  inputs:
    filename: 'C:\Users\user\Desktop\Fortify\Test\20210111\webgoat_test.bat'
    modifyEnvironment: false
    echo See https://aka.ms/yaml


- task: FortifySCA@7
  inputs:
    runBuildTranslate: true
    applicationType: 'java'
    fortifySourceTranslate: 'test'
    fortifyBuildId: '20201224_4'
    runFortifyRulepackUpdate: false
    runFortifyClean: true
    scaVerbose: true
    scaDebug: true
    runFortifyScan: true
    fortifyScanType: 'LocalScan'

