# Starter pipeline
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: |
      sourceanalyzer -b test -clean
      sourceanalyzer -b test -cp "C:\Program Files\Fortify\Fortify_SCA_and_Apps_20.2.0\Samples\advanced\webgoat\**\*.jar" "C:\Program Files\Fortify\Fortify_SCA_and_Apps_20.2.0\Samples\advanced\webgoat"
      sourceanalyzer -b test -scan -f "C:\Users\user\Desktop\Fortify\Test\20210111\test.fpr"
    workingDirectory: 'C:\Program Files\Fortify\Fortify_SCA_and_Apps_20.2.0\bin\sourceanalyzer.exe'