# Starter pipeline
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: FortifySCA@7
  inputs:
    runBuildTranslate: true
    applicationType: 'java'
    fortifySourceTranslate: 'test'
    fortifyBuildId: '20201224_4'
    runFortifyRulepackUpdate: false
    runFortifyClean: true
    scaVerbose: true
    scaDebug: true
    runFortifyScan: true
    fortifyScanType: 'LocalScan'

