# Starter pipeline
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: InstallFortifySCA@7
  inputs:
    InstallerPath: 'C:\Users\user\Desktop\Fortify\Fortify_19.20\Fortify_SCA_and_Apps_19.2.0_windows_x64.exe'
    VS2015: false
    LicenseFile: 'C:\Users\user\Desktop\Fortify\Fortify_19.20\fortify.license'
    RunFortifyRulepackUpdate: false
    ProxyPort: 80
- task: FortifySCA@7
  inputs:
    
    licenseFile: 'C:\Users\user\Desktop\Fortify\Fortify_19.20\fortify.license'
    runBuildTranslate: true
    applicationType: 'java'
    buildClasspath: '**\*.jar'
    fortifyBuildId: '20201224_4'
    runFortifyRulepackUpdate: false
    runFortifyClean: true
    scaVerbose: true
    scaDebug: true
    runFortifyScan: true
    fortifyScanType: 'LocalScan'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

